cleaning and more helpful error messages

diff --git a/bin/install b/bin/install
--- a/bin/install
+++ b/bin/install
@@ -38,13 +38,10 @@ install_rust_analyzer() {
   local source_path="${tmp_download_dir}/rust-analyzer.gz"
 
   (
-    echo "$install_path"
-    echo "$source_path"
-    echo "$download_url"
     echo "∗ Downloading..."
     curl --silent --location --create-dirs --output "$source_path" "$download_url" || fail "Could not download rust $version"
     mkdir -p "$install_path/bin"
-    gunzip -c "$source_path" > "$install_path/bin/rust-analyzer" || fail "Could not uncompress"
+    gunzip -c "$source_path" > "$install_path/bin/rust-analyzer" || fail "Could not uncompress. Make sure gzip is installed."
     chmod +x "$install_path/bin/rust-analyzer"
 
     rm -rf "$tmp_download_dir"
