removed all the unnecessary steps

diff --git a/bin/install b/bin/install
--- a/bin/install
+++ b/bin/install
@@ -35,18 +35,16 @@ install_rust_analyzer() {
   local download_url="https://github.com/rust-analyzer/rust-analyzer/releases/download/${version}/rust-analyzer-${architechture}-${platform}.gz"
   local tmp_download_dir
   tmp_download_dir=$(mktemp -d -t rust_analyzer_tmp_XXXXXX)
-  local source_path="${tmp_download_dir}/rust-analyzer.tar.gz"
-  local distination_path="${tmp_download_dir}/dist"
+  local source_path="${tmp_download_dir}/rust-analyzer.gz"
 
   (
     echo "∗ Downloading..."
     curl --silent --location --create-dirs --output "$source_path" "$download_url" || fail "Could not download rust $version"
-    mkdir -p "$distination_path/bin"
-    gzip -c "$source_path" > cat "$distination_path/bin" || fail "Could not uncompress"
+    gzip -c "$source_path" > cat "$intall_path/bin/rust-analyzer" || fail "Could not uncompress"
 
     rm -rf "$tmp_download_dir"
 
-    echo "Downloading was successful!"
+    echo "Installation was successful!"
   ) || (
     rm -rf "$install_path"
     fail "An error occurred"
